download_page/urls.py
from django.urls import path
from . import views

app_name = 'download-page'
urlpatterns = [
    path('download/', views.download, name='download'),
]

download_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('', include('download_page.urls')),
]

download_page/models.py
from django.db import models

# Create your models here.

download_page/views.py
from django.http import HttpResponse

def download(request):
    filename = 'download_page.zip'

    response = HttpResponse('test', content_type='zip')
    response['Content-Disposition'] = f"attachment; filename={filename}"
    return response

download_project/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/index.html')

templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <style>
        body {
            background-color: black;
            color: white;
        }

        #title {
            font-size: 20px;
            font-family: sans-serif;
            text-align: center;
        }

        #content {
            font-size: 19px;
        }

        #download {
            font-size: 20px;
            background-color: white;
            border: 1px solid rgb(71, 71, 71);
            border-radius: 5px;
        }
        #download:hover {
            background-color: rgb(179, 179, 179);
        }
    </style>

    <script>
        function download() {
            window.location.replace({% url 'download-page:download' %});
        };
    </script>
</head>
<body>
    <div id="title">
        <h1>Download page!</h1>
    </div>
    <div id="content">
        <p>Hi, this is a simple django project that will just download a file to the user's computer.</p>
        <button id="download" onclick="download()">download</button>
    </div>
</body>
</html>